### ISSUE TITLE
Dumb noob question

### ISSUE THREAD

**Issue by Bradovman** [powenn/AltServer-Linux-ShellScript#1]
I am very new to this and very confused. So you are using the pre-built Altstore file from NyaMisty. Because i thought that only worked on x86. Or are you compiling it yourself for arm. Also looking through your commits you seemed to have changed the name from Altserver-Linux-arm64 to AltServer-Linux-ShellScript. Does this mean that you no longer support arm? The pine phone runs an Allwinner A64 which is an arm chip so you have managed to get it running on arm correct?

**Comment by powenn** [comment]
I am using "AltServer"  from NyaMisty
AltStore installation not work yet,I am finding the reason
I didn't compile AltServer for arm, but that works on my pinephone mobian, actually pinephone is arm64 
I changed name because the script should work on not only arm64

**Comment by turannul** [comment]
@powenn can i ask question, i have vps (using as personal vpn) i want to use remote AltDeamon if possible please. [I have recently updated to Debian 11]

**Comment by powenn** [comment]
> @powenn can i ask question, i have vps (using as personal vpn) i want to use remote AltDeamon if possible please. [I have recently updated to Debian 11]

Install without usb connection ?

**Comment by turannul** [comment]
> > @powenn can i ask question, i have vps (using as personal vpn) i want to use remote AltDeamon if possible please. [I have recently updated to Debian 11]
> 
> Install without usb connection ?

yes without physical connection with usbflux 
https://github.com/corellium/usbfluxd

**Comment by powenn** [comment]
> > > @powenn can i ask question, i have vps (using as personal vpn) i want to use remote AltDeamon if possible please. [I have recently updated to Debian 11]
> 
> > 
> 
> > Install without usb connection ?
> 
> 
> 
> yes without physical connection with this 
> 
> https://github.com/corellium/usbfluxd

That would be interesting,but as known information from AltServer-Linux,it has mention that AltServer over Network not support running as AltServer Daemon ,so even it is possible,until AltServer-Linux update we can't reach it,and sadly fact I have to clarify that I am not a developer, I told this because some ppl thought I am,so actually I can't improve AltServer-Linux project.
