### ISSUE TITLE
Problem with installing Altstore

### ISSUE THREAD

**Issue by Rag3005** [powenn/AltServer-Linux-ShellScript#11]
I don't know how to solve.

`Alert: Installing AltStore with Multiple AltServers Not Supported
    Please use the same AltServer you previously used with this Apple ID, or else apps installed with other AltServers will stop working.`

**Comment by powenn** [comment]
> I don't know how to solve.
> 
> `Alert: Installing AltStore with Multiple AltServers Not Supported Please use the same AltServer you previously used with this Apple ID, or else apps installed with other AltServers will stop working.`

I think you can ignore that
