### ISSUE TITLE
Installing Altserver-Linux

### ISSUE THREAD

**Issue by hammyexe** [powenn/AltServer-Linux-ShellScript#18]
Can you make a video on how to install Altserver-Linux, I am not very smart and would appreciate if you could do that.

**Comment by powenn** [comment]
> Can you make a video on how to install Altserver-Linux, I am not very smart and would appreciate if you could do that.

It doesn't need to install,it's a executable file,just get the release and run ./run.sh,for first time run,run this instead chmod +x run.sh && ./run.sh
