### ISSUE TITLE
Issue installing Alstore

### ISSUE THREAD

**Issue by hammyexe** [powenn/AltServer-Linux-ShellScript#22]
I get an error saying, "A device with this number 'example numbers' already exists on this team (35) But I do not have it installed.

**Comment by powenn** [comment]
> I get an error saying, "A device with this number 'example numbers' already exists on this team (35) But I do not have it installed.

Did you jailbreak with unc0ver untether ?,I met the same problem due to using unc0ver untether

**Comment by hammyexe** [comment]
> > I get an error saying, "A device with this number 'example numbers' already exists on this team (35) But I do not have it installed.
> 
> Did you jailbreak with unc0ver untether ?,I met the same problem due to using unc0ver untether 

No I did not

**Comment by hammyexe** [comment]
> > > > I get an error saying, "A device with this number 'example numbers' already exists on this team (35) But I do not have it installed.
> 
> > > 
> 
> > > 
> 
> > > Did you jailbreak with unc0ver untether ?,I met the same problem due to using unc0ver untether
> 
> > 
> 
> > No I did not
> 
> 
> 
> Could you try others devices to test ?

It works with any other device but not mine

**Comment by powenn** [comment]
> > > > > I get an error saying, "A device with this number 'example numbers' already exists on this team (35) But I do not have it installed.
> > 
> > > > 
> > 
> > > > 
> > 
> > > > Did you jailbreak with unc0ver untether ?,I met the same problem due to using unc0ver untether
> > 
> > > 
> > 
> > > No I did not
> > 
> > 
> > 
> > Could you try others devices to test ?
> 
> It works with any other device but not mine

I think it's not script issue,try to ask it in AltServer-Linux issue

**Comment by hammyexe** [comment]
Ok thanks

**Comment by powenn** [comment]
Please try the latest release, this issue should be solved
