### ISSUE TITLE
This script does not have the fix from NyaMisty's repo to support iOS 15

### ISSUE THREAD

**Issue by intelgen** [powenn/AltServer-Linux-ShellScript#26]
Hi, there is a fix here: [](https://github.com/NyaMisty/AltSign-Linux/pull/1) to fix support iOS 15.XX.

Could you please merge this fix so we can have it working on iOS 15.

I thought maybe a re-install may fix things but then I also ran into the "A device with number 'xxxxxx' already exists on this team." error.

Just thought I'd note these 2 issues because I can't see them listed.
I know other users are suffering with these too.

Cheers

**Comment by powenn** [comment]
> Hi, there is a fix here: [](https://github.com/NyaMisty/AltSign-Linux/pull/1) to fix support iOS 15.XX.
> 
> 
> 
> Could you please merge this fix so we can have it working on iOS 15.
> 
> 
> 
> I thought maybe a re-install may fix things but then I also ran into the "A device with number 'xxxxxx' already exists on this team." error.
> 
> 
> 
> Just thought I'd note these 2 issues because I can't see them listed.
> 
> I know other users are suffering with these too.
> 
> 
> 
> Cheers

I have built it ,and it should be publish soon,not sure about did that fix iOS 15 issues ,I don't have iOS 15 devices,but "A device with number 'xxxxxx' already exists on this team." error still exists ,tested with my iPhone 11 Pro but 6s works fine,they both are on iOS 14,and the build fix x64 daemon problems so the size x64 release will be smaller

**Comment by powenn** [comment]
Try this
 https://github.com/powenn/AltServer-LinuxGUI/releases/download/0.1.3/AltServer-x86_64

**Comment by powenn** [comment]
AltServer Binary Updated
