### ISSUE TITLE
Instructions for existing Altstore installation (Apple ID error -36607)

### ISSUE THREAD

**Issue by lyh16** [powenn/AltServer-Linux-ShellScript#28]
Hi.

I already have AltStore installed on my iPhone from a Windows device. I am trying to get your script and GUI to work on my Ubuntu 20.04 device and just tried hitting the "Install" menu to get the AltServer-Linux_ShellScript to log in with my Apple account, but I keep getting "Unable to sign you in to your Apple ID. Try again later. (-36607)".

As per your answer on other issues related to the error -36607, I have tried deleting the Ubuntu device from the list of trusted devices on my iPhone and re-trusted the device. But this is not working either. One anomaly I am seeing during the CLI login procedure is that the date is set as "Date: 1899-12-31T00:00:00+0827". Maybe this contributes to the issue?

I attach a censored version of my terminal output for your information.
Please advise.

Thanks.

[terminal_output.txt](https://github.com/powenn/AltServer-Linux-ShellScript/files/8314553/terminal_output.txt)

**Comment by powenn** [comment]
> Hi.
> 
> 
> 
> I already have AltStore installed on my iPhone from a Windows device. I am trying to get your script and GUI to work on my Ubuntu 20.04 device and just tried hitting the "Install" menu to get the AltServer-Linux_ShellScript to log in with my Apple account, but I keep getting "Unable to sign you in to your Apple ID. Try again later. (-36607)".
> 
> 
> 
> As per your answer on other issues related to the error -36607, I have tried deleting the Ubuntu device from the list of trusted devices on my iPhone and re-trusted the device. But this is not working either. One anomaly I am seeing during the CLI login procedure is that the date is set as "Date: 1899-12-31T00:00:00+0827". Maybe this contributes to the issue?
> 
> 
> 
> I attach a censored version of my terminal output for your information.
> 
> Please advise.
> 
> 
> 
> Thanks.
> 
> 
> 
> [terminal_output.txt](https://github.com/powenn/AltServer-Linux-ShellScript/files/8314553/terminal_output.txt)

I think it should be ask in AltServer Linux ,it wasn't cause by the script

**Comment by lyh16** [comment]
I have resolved this issue and wish to share the steps I took.
Any feedback on whether my solution worked for anyone else would be helpful for future visitors of this page.

1. Install [AltServer-LinuxGUI](https://github.com/powenn/AltServer-LinuxGUI) a sister project by @powenn. I used version 0.1.6, the latest version as of April 1st, 2022.
2. Click on the tray icon for the AltServer-LinuxGUI and select "Pair".
3. Select "Trust" when a message asking whether or not to trust your Linux device appears on your iPhone.
4. Select "Allow" for the login attempt prompt that follows, on your iPhone.
5. Note the 6 digit OTP that shows on your iPhone.
6. Enter the previously noted 6 digit OTP into the OTP prompt that shows on your iPhone.
7. Open the AltStore app on your iPhone and hit "Refresh All" for your IPA apps.
=> Refresh is successful.

**Comment by powenn** [comment]
That called 2FA ,and actually both shell script and GUI editions can enter that when the 2FA required,36607 error wasn't caused by that,and I think the solution is waiting for few hours or several days,still not sure about it

**Comment by ddeler** [comment]
> I have resolved this issue and wish to share the steps I took. Any feedback on whether my solution worked for anyone else would be helpful for future visitors of this page.
> 
>     1. Install [AltServer-LinuxGUI](https://github.com/powenn/AltServer-LinuxGUI) a sister project by @powenn. I used version 0.1.6, the latest version as of April 1st, 2022.
> 
>     2. Click on the tray icon for the AltServer-LinuxGUI and select "Pair".
> 
>     3. Select "Trust" when a message asking whether or not to trust your Linux device appears on your iPhone.
> 
>     4. Select "Allow" for the login attempt prompt that follows, on your iPhone.
> 
>     5. Note the 6 digit OTP that shows on your iPhone.
> 
>     6. Enter the previously noted 6 digit OTP into the OTP prompt that shows on your iPhone.
> 
>     7. Open the AltStore app on your iPhone and hit "Refresh All" for your IPA apps.
>        => Refresh is successful.

I can't figure out how to install it on Fedora, since it just builds a .deb file, so no luck in that front for me. Any way to do the same thing without the GUI version? I can't seem to find a "trust" parameter to replicate the same behaviour
