### ISSUE TITLE
Provide make instructions

### ISSUE THREAD

**Issue by dmunozv04** [powenn/AltServer-Linux-ShellScript#3]
Could you publish the process that you used to get the AltServer and AltserverDaemon executables?, as they only work for x64 right now. It would be great to have this running on a sbc like a RaspberryPi

**Comment by dmunozv04** [comment]
Thanks, I’ll give it a go

**Comment by dmunozv04** [comment]
It gives me an error: ‘’’cannot execute binary file: Exec format error’’’ and my architecture is: ‘’’aarch64’’’

**Comment by powenn** [comment]
> It gives me an error: `cannot execute binary file: Exec format error` and my architecture is: `aarch64`

Seems the release not support yet
