### ISSUE TITLE
apple id or password is incorrect

### ISSUE THREAD

**Issue by Mcprosehp** [powenn/AltServer-Linux-ShellScript#30]
I been having this issue and I have retried multiple times where im trying to install Alt store i enter my information and I get this error (title). One time i turned on my mobile hotspot to see if that would fix anything but I got a different error saying "Failed to read HTTP status line.".

**Comment by LuNeder** [comment]
Same here, wrong password error. After following [this from dev's twitter](https://twitter.com/powen00hsiao/status/1517667545574445056?s=69&t=stoptracking), devices pair OK, but I started to get the unable to sign in try again later error instead (like in #23) when installing AltStore. Installing netmuxd as suggested later on the same twitter thread and running it as suggested on the [readme](https://github.com/jkcoxson/netmuxd#altstore) gives me "No device found, is it plugged in?" error when pairing.

**Comment by LuNeder** [comment]
Update: seems to be a problem with Apple's stuff, there's a workaround on [NyaMisty's releases page](https://github.com/NyaMisty/AltServer-Linux/releases/tag/v0.0.5) by using your own server
