### ISSUE TITLE
It's not working after updated the laterest version.

### ISSUE THREAD

**Issue by vvlaw** [powenn/AltServer-Linux-ShellScript#32]
it's stuck in here:

For more information: https://github.com/powenn/AltServer-Linux-ShellScript

Enter OPTION to continue
Starting netmuxd
Starting mDNS discovery
Listening on /var/run/usbmuxd
Adding device 00008020-001254880E08002E

**Comment by vvlaw** [comment]
For now , sticking in the usbmuxd...

#####################################
#  Welcome to the AltServer script  #
#####################################

ScriptUsage: [OPTION]

OPTIONS

  i, --Install AltStore or ipa files
    Install AltStore or ipa files to your device
  w, --Switch to wifi Daemode mode (Default using it after launch)
    Switch and restart to wifi Daemode mode to refresh apps or AltStore
  t, --Switch to usb tethered Daemode mode
    Switch and restart to usb tethered Daemode mode to refresh apps or AltStore
  e, --Exit
    Exit script
  h, --Help
    Show this message
  p, --Pair
    Pair device
  u, --Update
    Update this script or AltServer

For more information: https://github.com/powenn/AltServer-Linux-ShellScript

Enter OPTION to continue
Starting netmuxd
Starting mDNS discovery
Listening on /var/run/usbmuxd

**Comment by powenn** [comment]
Have you installed all required dependencies?

**Comment by vvlaw** [comment]
because I am using Archlinux now, I think I added some dependencies yet except libavahi-compat-libdnssd-dev, I can not find this by the yay or pacman method. Is this the problem ?

**Comment by vvlaw** [comment]
I think I have already install it yet...

warning: avahi-0.8+22+gfd482a7-3 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

https://archlinux.org/packages/extra/x86_64/avahi/

Service Discovery for Linux using mDNS/DNS-SD -- compatible with Bonjour

are these the same packages?

**Comment by powenn** [comment]
Could you describe what's your meaning of it stuck,seems it detected one device in your first comment

**Comment by powenn** [comment]
If switching back to usb option,try re plug your device and pair

**Comment by vvlaw** [comment]
> Could you describe what's your meaning of it stuck,seems it detected one device in your first comment

For more information: https://github.com/powenn/AltServer-Linux-ShellScript

[sudo] password for vvlaw: 
Enter OPTION to continue
Starting netmuxd
Starting mDNS discovery
Listening on /var/run/usbmuxd



The stuck means the program sticking in " Listening on /var/run/usbmuxd

it's not working .

**Comment by powenn** [comment]
I will take time to test it on Manjaro and the other arch based distribution

**Comment by vvlaw** [comment]
Ok. Thank you very much

**Comment by powenn** [comment]
Problem found , I am fixing it

**Comment by vvlaw** [comment]
how to use it ? it also stuck in " 
Adding device 000*****-******

it did not add the device succesfully. so I can not use AltStore App to Refresh All.

**Comment by vvlaw** [comment]
But when I use the PyScript to refresh the apps, it can be worked.

Enter OPTION to continue :d
SUCCESS: Paired with device 00008020-001254880E08002E
Enter OPTION to continue :

**Comment by powenn** [comment]
Python edition have been not updated for long time,network refresh should be available in shell edition

**Comment by vvlaw** [comment]
I mean that It pause on Adding device, so I can not operate next step.

**Comment by Macleykun** [comment]
any update on this?

**Comment by jurassicjordan** [comment]
also having this problem, "[2022-10-25T03:53:53Z ERROR netmuxd::heartbeat] Failed to create heartbeat client for udid 00008101-0006089C1478001E: UnknownError
Removing 00008101-0006089C1478001E" 
is this getting fixed?

**Comment by Macleykun** [comment]
@jurassicjordan i fixed it by switching from wifi to tethered and then back to wifi mode.
See: https://github.com/jkcoxson/netmuxd/issues/5#issuecomment-1290902747
This is actually a netmuxd issue :) i hope this helps resolve the issue for ya!
