### ISSUE TITLE
Unknown Options

### ISSUE THREAD

**Issue by CannibalToast** [powenn/AltServer-Linux-ShellScript#34]
![image](https://user-images.githubusercontent.com/54596711/178090651-4ceecc95-c2d8-422d-8565-2677ad4b22d3.jpeg)

I can't seem to start the script. I downloaded the correct version of alt server and all of its dependencies and am running as a super user. I'm not sure what the issue could be

**Comment by powenn** [comment]
No device paired

**Comment by CannibalToast** [comment]
> No device paired 

Unfortunately it still looks like I'm still getting the same error even though I just paired it. ![image](https://user-images.githubusercontent.com/54596711/178198545-a7388c48-c64a-4d50-bded-6564defe2de3.jpeg)

**Comment by powenn** [comment]
Wait a minute the length of that command is too short, seems like it haven't input your UDID , are you trying install without usb connection?

WiFi installation is not supported in the script,you can only do WiFi refresh

**Comment by CannibalToast** [comment]
> Wait a minute the length of that command is too short, seems like it haven't input your UDID , are you trying install without usb connection?
> 
> WiFi installation is not supported in the script,you can only do WiFi refresh 

I am over USB. I paired it and it paired successfully. So I'm not sure what the problem is.

**Comment by powenn** [comment]
Try t option, replug and i

**Comment by powenn** [comment]
Did you install all required dependencies?
