### ISSUE TITLE
Worked once, isn't working anymore...

### ISSUE THREAD

**Issue by Jujube54** [powenn/AltServer-Linux-ShellScript#35]
If I try to install Altstore, it signs it then tells me this: 

Signing Progress: 1
Alert: Could not install AltStore.ipa to unknown.
    There was an error connecting to the device. Make sure you have trusted this device with your computer and WiFi sync is enabled.

If I try to restart Daemon mode, it tells me this: 

/home/jujube/Downloads/AltServer-armv7/run.sh: line 111:  9612 Terminated              ./AltServer &> /dev/null

I'm running this on Ubuntu 18.04, which I can't update because it's running on my hacked switch...

**Comment by ramondunker** [comment]
I'm having the same issue. Did you fix it?

**Comment by powenn** [comment]
T option,there's no WiFi installation support

**Comment by Jujube54** [comment]
> 

I didn’t. Same issue on iPhone and iPad, could do one install, then never anymore. I was using a cable, and the pairing was successful every time…

**Comment by powenn** [comment]
AltStore ipa file missing,you might delete it
