### ISSUE TITLE
Nethunter kali linux Rooted Android device

### ISSUE THREAD

**Issue by AyazAhmad12** [powenn/AltServer-Linux-ShellScript#38]
Everything work udid id get 
But usb trust device not working
Im using simple otg cable
Sorry for my bad English

**Comment by AyazAhmad12** [comment]
![Screenshot_20220801-144839.jpg](https://user-images.githubusercontent.com/100126391/182141874-6934f69d-9748-444a-ae8d-4341a16f5677.jpg)

**Comment by AyazAhmad12** [comment]
![Screenshot_20220801-145610.jpg](https://user-images.githubusercontent.com/100126391/182142700-654b75cb-e8e3-40fe-a220-d7392ebad82e.jpg)

**Comment by AyazAhmad12** [comment]
Kindly work on android support

**Comment by powenn** [comment]
Could you show me how you connecting the devices?
