### ISSUE TITLE
Identity is no longer valid

### ISSUE THREAD

**Issue by SternXD** [powenn/AltServer-Linux-ShellScript#39]
So I've used this before and it was working but I don't know what changed but this is all I get now when I try to install AltStore

Steps I've tried:
1. I've tried different Apple IDS
2. I've tried different distros
3. And I've tried making sure the date and the time was set 
![IMG_1644](https://user-images.githubusercontent.com/70122891/184753817-4f92cf0e-bfb1-4889-80cc-cd3e2cc13413.JPG)

**Comment by powenn** [comment]
Seems the version of AltStore is revoked
Try replace it
curl -L https://cdn.altstore.io/file/altstore/apps/altstore/1_5_1.ipa > AltStore.ipa

**Comment by SternXD** [comment]
i've tried doing that one and the beta

**Comment by powenn** [comment]
iOS version?

**Comment by SternXD** [comment]
iOS 16.0 Beta 6 but that shouldn’t be an issue because it worked before?

**Comment by powenn** [comment]
It worked on Beta 6 before ?

**Comment by SternXD** [comment]
I was on Beta 5 at the time of this screenshot but i just updated an tried again and it was doing the same thing and i even restored back to 15.6 and it was still doing this same error message.

**Comment by SternXD** [comment]
I will say when I tested it with iOS 16 Beta 6 it was complaining about not having a Developer Disk Image but it might not be related I'm not sure

**Comment by SternXD** [comment]
Closing because I fixed it by me keeping on switching distros and finally finding one that works
