### ISSUE TITLE
Not working on Raspberry Pi OS

### ISSUE THREAD

**Issue by Dylan96** [powenn/AltServer-Linux-ShellScript#4]
Can't install AltStore using a Raspberry Pi 3 with latest Pi OS

```
./install.sh: line 24: ./AltServer: cannot execute binary file: Exec format error
Finished
```

System info:
```
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10

Linux kernel: 5.10.63-v7+
```

**Comment by powenn** [comment]
> Can't install AltStore using a Raspberry Pi 3 with latest Pi OS
> 
> 
> 
> ```
> 
> ./install.sh: line 24: ./AltServer: cannot execute binary file: Exec format error
> 
> Finished
> 
> ```
> 
> 
> 
> System info:
> 
> ```
> 
> Description:    Raspbian GNU/Linux 10 (buster)
> 
> Release:        10
> 
> 
> 
> Linux kernel: 5.10.63-v7+
> 
> ```
> 
> 

The AltServer-Linux release not support its architecture

**Comment by powenn** [comment]
> Can't install AltStore using a Raspberry Pi 3 with latest Pi OS
> 
> ```
> ./install.sh: line 24: ./AltServer: cannot execute binary file: Exec format error
> Finished
> ```
> 
> System info:
> 
> ```
> Description:    Raspbian GNU/Linux 10 (buster)
> Release:        10
> 
> Linux kernel: 5.10.63-v7+
> ```

wait, how about different OS,could u please help for test ?

**Comment by powenn** [comment]
> Can't install AltStore using a Raspberry Pi 3 with latest Pi OS
> 
> ```
> ./install.sh: line 24: ./AltServer: cannot execute binary file: Exec format error
> Finished
> ```
> 
> System info:
> 
> ```
> Description:    Raspbian GNU/Linux 10 (buster)
> Release:        10
> 
> Linux kernel: 5.10.63-v7+
> ```

How about different OS,could u please help for test ?

**Comment by Bradovman** [comment]
Are you running the 64 bit or the 32 bit version of raspberry Pi OS?

**Comment by Dylan96** [comment]
armv7l, 32bit

**Comment by Bradovman** [comment]
I have had luck using the official AltServer for linux Armv7 build [here](https://github.com/NyaMisty/AltServer-Linux/releases/tag/v0.0.2-1). Try downloading that in the scripts directory and renaming it to "Altserver".

**Comment by Dylan96** [comment]
Yeah will try that

**Comment by powenn** [comment]
> I have had luck using the official AltServer for linux Armv7 build [here](https://github.com/NyaMisty/AltServer-Linux/releases/tag/v0.0.2-1). Try downloading that in the scripts directory and renaming it to "Altserver".

I will update script

**Comment by Dylan96** [comment]
> I have had luck using the official AltServer for linux Armv7 build [here](https://github.com/NyaMisty/AltServer-Linux/releases/tag/v0.0.2-1). Try downloading that in the scripts directory and renaming it to "Altserver".

I tried with v0.0.02-1, the .ipa installs fine but it crashes at launch... is it working for you?
