### ISSUE TITLE
./AltServer: line 1: Not: command not found

### ISSUE THREAD

**Issue by razor1995** [powenn/AltServer-Linux-ShellScript#40]
Hi,
When using latest version of your script (0.4.0) got error:
`./AltServer: line 1: Not: command not found`
when trying to install AltStore or any other ipa on my device. 
![image](https://user-images.githubusercontent.com/99041755/186899766-729a4d3c-df4e-4f24-b976-520db78fc65c.png)
Got the same error on my RaspberryPi Raspbian and Ubuntu on my desktop.
Also it's not downloading netmuxd - I need to download it manually and place in this script directory.

**Comment by powenn** [comment]
Don't download netmuxd,it's unsupported for your arch ,try run AltServer command to install file manually,if it shows the same error then it's not a script issue

**Comment by powenn** [comment]
What's the result of 
uname -m

**Comment by razor1995** [comment]
`lukasz@E7240:~/alt/AltServer-x86_64$ uname -m
x86_64
`
So, right now console log looks like this:
`lukasz@E7240:~/alt/AltServer-x86_64$ sudo ./run.sh
Checking source
    
#####################################
#  Welcome to the AltServer script  #
#####################################

ScriptUsage: [OPTION]

OPTIONS

  i, --Install AltStore or ipa files
    Install AltStore or ipa files to your device
  w, --Switch to wifi Daemode mode (Default using it after launch)
    Switch and restart to wifi Daemode mode to refresh apps or AltStore
  t, --Switch to usb tethered Daemode mode
    Switch and restart to usb tethered Daemode mode to refresh apps or AltStore
  e, --Exit
    Exit script
  h, --Help
    Show this message
  p, --Pair
    Pair device
  u, --Update
    Update this script or AltServer

For more information: https://github.com/powenn/AltServer-Linux-ShellScript

Enter OPTION to continue
Starting netmuxd
Starting mDNS discovery
Listening on /var/run/usbmuxd
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Unknown packet type: Connect
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22
`
And "adding device" takes forever.

**Comment by powenn** [comment]
All dependencies installed?

**Comment by Macleykun** [comment]
> `uname -m x86_64 ` Few restarts and cachemode changes solved the issue. But when I try to install/refresh any app from AltStore via Wi-Fi I got error: "AltStore could not find this device". When using the cable, everything's works fine. Error: `Adding device 1ec43bd5b5fd3f785402df0072304eec9f28ab22 [2022-08-26T16:03:09Z ERROR netmuxd::heartbeat] Failed to create heartbeat client for udid 1ec43bd5b5fd3f785402df0072304eec9f28ab22: UnknownError `

heya, ya still having the issue? have ya tried installing the dependencies first? Otherwise ya can close the issue :).

**Comment by Macleykun** [comment]
hey @razor1995 ya still having this issue or not?
