### ISSUE TITLE
run.sh broken after update: Unknown Options

### ISSUE THREAD

**Issue by Tup0lev** [powenn/AltServer-Linux-ShellScript#42]
The script is unusable after update. 

/AltServer-x86_64$ ./run.sh 
Checking source
    
#####################################
#  Welcome to the AltServer script  #
#####################################

ScriptUsage: [OPTION]

OPTIONS

  i, --Install AltStore or ipa files
    Install AltStore or ipa files to your device
  w, --Switch to wifi Daemode mode (Default using it after launch)
    Switch and restart to wifi Daemode mode to refresh apps or AltStore
  t, --Switch to usb tethered Daemode mode
    Switch and restart to usb tethered Daemode mode to refresh apps or AltStore
  e, --Exit
    Exit script
  h, --Help
    Show this message
  p, --Pair
    Pair device
  u, --Update
    Update this script or AltServer

For more information: https://github.com/powenn/AltServer-Linux-ShellScript

Enter OPTION to continue
Starting netmuxd
Starting mDNS discovery
Listening on /var/run/usbmuxd
i

----------------------
InstallUsage: [OPTION]

OPTIONS

  1, --Install AltStore
    Install AltStore to your device
  2, --Install ipa files
    Install ipa files to your device
  b, --Back
    Back to previous script
Enter OPTION to continue
1
Do you want to use saved Account ? [y/n]
y
Which account you want to use ? 
     1	johndoe@example.com,password123
please enter the number 
1
Unknown options: johndoe@example.com ./AltStore.ipa 
<<  Back to AltServer script  >>
Enter OPTION to continue
Adding device MY_DEVICEID
Adding device MY_DEVICEID
Unknown packet type: Connect

**Comment by powenn** [comment]
Switch to tether mode for installation , There is no wifi mode installation support yet

**Comment by Staubgeborener** [comment]
@powenn I would leave the issue open if i were you. i have the same error and am in tether mode. The problem occurs only after the update of your script. 

Step by step:
1. Connect iOS device via cable to AltServer
2. run `./run.sh`
3. `adding device [...]` loop occurs

I already deleted the plist file in `/var/lib/lockdown/` and manually ran `idevicepair pair`. Still the same issue. After that I deleted the plist file again and just ran `./run.sh`, so your script paired the device. Same problem. As I said, with tether so NO wifi.

**Comment by powenn** [comment]
Try plug in after run the script and switch to tether mode then pair

**Comment by powenn** [comment]
And I just removed the logo after this update,if people missing it, I can just add it back

**Comment by powenn** [comment]
@Staubgeborener check messages above
