### ISSUE TITLE
aarch64 support (WiFi-refresh)

### ISSUE THREAD

**Issue by Macleykun** [powenn/AltServer-Linux-ShellScript#43]
Her pownn,

I talked with @jkcoxson and he has added aarch64 support & is releasing the binary for it aswell now!

See: https://github.com/jkcoxson/netmuxd/releases/tag/v0.1.3

This means that the reason why wi-fi refresh for 64-bit rpi's couldn't be added is now resolved!

There's no official netmuxd release for aarch64,so no arrch64 support

_Originally posted by @powenn in https://github.com/powenn/AltServer-Linux-ShellScript/issues/41#issuecomment-1242827336_

Is it possible to update the script to include this newly added architecture?

Looking forward to your reply!! <3

**Comment by powenn** [comment]
Did you try with the instruction from netmuxd repo? Is that working for aarch64 ?

**Comment by Macleykun** [comment]
> Did you try with the instruction from netmuxd repo? Is that working for aarch64 ?
> 
> I test it on both x86_64 and aarch64 with my script ,they both not working ,always shows creating plist

Never used it myself. @jkcoxson could you help us?

**Comment by Macleykun** [comment]
Also, @powenn you can join his server here: https://discord.gg/RgpFBX3Q3k

**Comment by powenn** [comment]
To test it with the script,just add aarch64 to netmuxd available variable and modify the curl command to download the latest release

**Comment by Macleykun** [comment]
> To test it with the script,just add aarch64 to netmuxd available variable and modify the curl command to download the latest release or place it manually if using older release or testing one

Sadly I can’t test it yet (currently going on holidays). So I’ll personally be testing this somewhere next week :) 

Meanwhile, @HeyMeco would ya mind to test this one out :) ?

**Comment by HeyMeco** [comment]
> Meanwhile, @HeyMeco would ya mind to test this one out :) ?
`Starting netmuxd`
`Starting mDNS discovery for _apple-mobdev2._tcp.local with mdns`

looks good I just couldn't try pairing a device yet since I apparently have no USB-A to lightining cables left

**Comment by powenn** [comment]
Usb-c to lightening can pair devices

**Comment by andre1808** [comment]
Hey. You pointed me here (I suppose? :)), but I'm not sure how this helps me :\
This Starting netmuxd and mDNS discovery came up as well. But since then it's running that creating plist part for hours now :(

**Comment by powenn** [comment]
So it wasn't a script issue,I guess even you followed the instruction from netmuxd repo,you will get the same result

**Comment by andre1808** [comment]
Well not sure about that. 
Netmuxd is available for more architectures now, so the limitation to x86/x64 isn’t necessary anymore. 
The disclosed prebuild altserver doesn’t seem to be working for everyone. But I guess that’s not really something you could deal with with your script. 

I’m still not sure about that plist stuff. What is this? 😅

**Comment by jkcoxson** [comment]
I’ll give it a look

**Comment by jkcoxson** [comment]
Testing on aarch64-apple-darwin and x86_64-linux-gnu, netmuxd is operating as expected (besides weird log spam). Would somebody mind sending a log with ``RUST_LOG=netmuxd=info``?

**Comment by powenn** [comment]
> Testing on aarch64-apple-darwin and x86_64-linux-gnu, netmuxd is operating as expected (besides weird log spam). Would somebody mind sending a log with ``RUST_LOG=netmuxd=info``?

Did you tested with AltServer or netmuxd only

**Comment by Macleykun** [comment]
I'll summarize how i now have it setup:
This is what's happening at the moment with the latest release:
![image](https://user-images.githubusercontent.com/26381427/191572216-b3e8df7b-cc5f-449c-a5b8-d0b322bfcecb.png)

(this keeps going on even when exiting the script)

I've editted the script slighty by replacing the available archs to aarch64
NETMUXD_AVAILABLE_ARCHS=("aarch64")

the curl command is changed to a static one
curl -L https://github.com/jkcoxson/netmuxd/releases/download/v0.1.3/aarch64-linux-netmuxd > netmuxd

Now i set the env var and this is the output:

![image](https://user-images.githubusercontent.com/26381427/191572919-4a386c16-85d6-4c80-8bd0-eba44df52331.png)

Is this what you wanted to see @jkcoxson ?

**Comment by Macleykun** [comment]
Did a proper debug:

```
macley@raspberrypi:~/AltServer-Linux-ShellScript $ export RUST_LOG=netmuxd=info
macley@raspberrypi:~/AltServer-Linux-ShellScript $ ls
AltServer  AltStore.ipa  ipa  LICENSE  main  netmuxd  photos  README.md  run.sh  saved.txt  update.sh  version
macley@raspberrypi:~/AltServer-Linux-ShellScript $ ./run.sh ^C
macley@raspberrypi:~/AltServer-Linux-ShellScript $ cd ^C
macley@raspberrypi:~/AltServer-Linux-ShellScript $ ./netmuxd
Starting netmuxd
[2022-09-21T18:24:40Z INFO  netmuxd] Logger initialized
[2022-09-21T18:24:40Z INFO  netmuxd] Collected arguments, proceeding
[2022-09-21T18:24:40Z INFO  netmuxd::devices] Using system default plist storage
[2022-09-21T18:24:40Z INFO  netmuxd] Created new central data
Starting mDNS discovery for _apple-mobdev2._tcp.local with mdns
[2022-09-21T18:24:40Z INFO  netmuxd] Deleting old Unix socket
[2022-09-21T18:24:40Z INFO  netmuxd] Binding to new Unix socket
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', src/main.rs:139:79
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2022-09-21T18:24:45Z INFO  netmuxd::devices] Getting UDID for MAC: "24:5e:48:9c:99:f3"
Creating plist 1225094919
Creating plist 774086877
Creating plist 4254790193
[2022-09-21T18:24:49Z INFO  netmuxd::devices] Getting UDID for MAC: "60:06:e3:1f:2e:16"
Creating plist 1080010214
Creating plist 2525171759
Creating plist 2661630535
[2022-09-21T18:24:50Z INFO  netmuxd::devices] Getting UDID for MAC: "60:06:e3:1f:2e:16"
Creating plist 3874530265
Creating plist 1409631651
Creating plist 3568191554
[2022-09-21T18:24:50Z INFO  netmuxd::devices] Getting UDID for MAC: "24:5e:48:9c:99:f3"
Creating plist 2855442252
Creating plist 2694611728
Creating plist 2739548227
[2022-09-21T18:24:52Z INFO  netmuxd::devices] Getting UDID for MAC: "60:06:e3:1f:2e:16"
Creating plist 1071889904
Creating plist 280241683
Creating plist 414090823
[2022-09-21T18:24:55Z INFO  netmuxd::devices] Getting UDID for MAC: "24:5e:48:9c:99:f3"
Creating plist 1800698422
Creating plist 1380308215
Creating plist 3796507001
[2022-09-21T18:24:56Z INFO  netmuxd::devices] Getting UDID for MAC: "60:06:e3:1f:2e:16"
Creating plist 4263789265
Creating plist 1948031866
Creating plist 3402201885
[2022-09-21T18:24:58Z INFO  netmuxd::devices] Getting UDID for MAC: "60:06:e3:1f:2e:16"
Creating plist 2237671522
Creating plist 1554311012
Creating plist 2284155611
^C
```

**Comment by jkcoxson** [comment]
Looks to me like there is no pairing file in /var/lib/lockdown
Do any of the pairing files there have your Mac address?

**Comment by Macleykun** [comment]
> This `00008110-001419211178801E.plist` has your Mac address listed under `WiFiMACAddress`? If so, can you change the export to `RUST_LOG=info`

Correct! The value here:
```
        <key>WiFiMACAddress</key>
        <string>24:5e:48:9c:99:f3</string>
```
is the actual mac adres. (i do have private wifi-adress on)

Here's the new log: https://hastebin.com/ilimojiqit.rb
(using hastebin to not make this issue longer then needed)

**Comment by jkcoxson** [comment]
You'll have to run with root again, netmuxd has to bind to /var/run/lockdown or extra config will have to be done to allow for it to run off of a TCP socket.

**Comment by powenn** [comment]
@Macleykun Did you figure out something?

**Comment by Macleykun** [comment]
> @Macleykun Did you figure out something?

so it's a netmuxd problem, quoting jkcoxson from discord:
```
jkcoxson — Yesterday at 21:49
I'm gonna have to look into the issue some more, I'm not sure why it's not finding your pairing files.
```

For now we have to wait for jkcoxson :) after it's working for aarch64, it's wiser to add the support for it into the script and wait for bug reports to come in :).

**Comment by Macleykun** [comment]
Dropping this here:
```
sudo apt install git -y
git clone https://github.com/powenn/AltServer-Linux-ShellScript.git
sudo apt-get install libavahi-compat-libdnssd-dev usbmuxd libimobiledevice6 libimobiledevice-utils -y
```
for when we can test again when plist building works :) <3

**Comment by Macleykun** [comment]
hey pownn, the next netmuxd will work on aarch64 too
are you able to test this yourself? I seem to have an issue with entering my apple creds.
https://github.com/powenn/AltServer-Linux-ShellScript/issues/46

I don't believe this is an issue with netmuxd

**Comment by jkcoxson** [comment]
I'll push updates to GitHub releases, I've fixed netmuxd with @Macleykun 's help.

**Comment by powenn** [comment]
> hey pownn, the next netmuxd will work on aarch64 too
> 
> are you able to test this yourself? I seem to have an issue with entering my apple creds.
> 
> https://github.com/powenn/AltServer-Linux-ShellScript/issues/46
> 
> 
> 
> I don't believe this is an issue with netmuxd 

I can test it next week

**Comment by powenn** [comment]
> I'll push updates to GitHub releases, I've fixed netmuxd with @Macleykun 's help.

Thanks for this update

**Comment by lolren** [comment]
Perfect. Thank you very much for the hard work. I can`t wait to have Altserver running on my Openvpn Raspberry pi server :D

**Comment by Macleykun** [comment]
Heya, great news!
Just managed to refresh and even install youtube while my windows pc altstore was off!

I did somehow had this error: -36607 even with a brand new apple account. Installing the alstore app first on my pc on my i device and then using the wifi refresh from altserver script works!

It even let's netmuxd run in the background, so it's super user friendly to keep you're apps signed!

What i did to test this:
1. Download the architecture of your choice here: https://github.com/powenn/AltServer-Linux-ShellScript/releases/tag/0.4.0
2. unzip it
3. Download the right netmuxd here: https://github.com/jkcoxson/netmuxd/releases
4. In the run.sh script, i editted the compatibility list to say aarch64 in my case.
5. I removed the certificate on my idevice, and first plugged it into my main pc, installed altstore on it.
6. I also signed in, refreshed once more with cable
7. then refresh but withoud cable (still works)
8. refresh again but now i closed altserver on my win (fails, can't find the server)
9. back to the linux machine, run the file with: sudo bash run.sh
10. on your idevice, refresh and it should work!
11. Install cercube with: https://routinehub.co/shortcut/13064/ (yes shameless self-advert)
12. Enjoy!

Big thanks to everyone again :) i looked out doing this for months! Can't wait for pownn to add the arch's he could also verify that work and be supported officially :D

**Comment by Macleykun** [comment]
> Perfect. Thank you very much for the hard work. I can`t wait to have Altserver running on my Openvpn Raspberry pi server :D

ah is it openvpn you need to remote refresh? any guide you followed :) ?
do let us know if you're refresh works with openvpn through celluar/wifi!

**Comment by lolren** [comment]
To install and run openvpn is easy : `wget https://github.com/angristan/openvpn-install/raw/master/openvpn-install.sh` ,  `bash install.sh`. Follow the install wizard, copy the .opvn file to the iphone, install openvpn client on the iphone. Remember to port forward the used port on your router. If you have dinamic IP, use [](https://freedns.afraid.org/) , make a free account and you connect from anywhere trough cellular data/wifi. the only missing piece of the puzzle is wifi refresh from netmuxd. Any questions please ask. Good luck.

**Comment by jkcoxson** [comment]
Alright sorry to burst y’all’s bubbles but
1. iOS will reject connections over cellular
2. netmuxd isn’t enough for VPN AltStore because mDNS has to go the other way for AltServer discovery.

This is something a [team](https://github.com/SideStore) of developers and I are actively trying to solve, but this will not work out of the box.

**Comment by andre1808** [comment]
I still can't make this work on my rpi3b  (armv7l) :(
netmuxd seems to be working. I've tried following the instructions by Macleykun (the pairing part seems to be missing though?), but wifi refresh simply doesn't work. On my iPhone it says it can't find the server.

Earlier today I was playing with that already. I was able to install altstore and refresh over cable.
But as soon as I disconnected the cable it gave me the 36607 error.
I'm running the anisette server on my NAS and I've also set ALTSERVER_ANISETTE_SERVER variable. It's also working, otherwise I would not have been able to install it.

So yeah, it's quite frustrating to me, since I'm also not a Linux expert and I wish I could make this work. But I just can't :(

**Comment by lolren** [comment]
> Alright sorry to burst y’all’s bubbles but
> 
> 1. iOS will reject connections over cellular
> 2. netmuxd isn’t enough for VPN AltStore because mDNS has to go the other way for AltServer discovery.
> 
> This is something a [team](https://github.com/SideStore) of developers and I are actively trying to solve, but this will not work out of the box.

Even with vpn? Vpn should be seen as a network. When I get back home I will try to make a vpn with my windows pc and see if i can connect to altserver.

**Comment by jkcoxson** [comment]
I can guarantee to you that I've had this exact same thought process and spent hours trying to make it work. A VPN still has a physical interface that it goes over, and iOS still detects this and blocks lockdown (the connection AltStore uses).

**Comment by jkcoxson** [comment]
> I still can't make this work on my rpi3b (armv7l) :( netmuxd seems to be working. I've tried following the instructions by Macleykun (the pairing part seems to be missing though?), but wifi refresh simply doesn't work. On my iPhone it says it can't find the server.
> 
> Earlier today I was playing with that already. I was able to install altstore and refresh over cable. But as soon as I disconnected the cable it gave me the 36607 error. I'm running the anisette server on my NAS and I've also set ALTSERVER_ANISETTE_SERVER variable. It's also working, otherwise I would not have been able to install it.
> 
> So yeah, it's quite frustrating to me, since I'm also not a Linux expert and I wish I could make this work. But I just can't :(
> 
> -edit- The plist spam however is gone. And netmuxd also gives me this output: Adding device UDID
> 
> However it's cycling between Adding and Removing UDID constantly.

I would try generating a new pairing file that supports WiFi sync. Usbmuxd is unable to generate them. You can use jitterbug pair to generate a new one, and replace the old pairing file in ``/var/lib/lockdown``

**Comment by powenn** [comment]
> Heya, great news!
> 
> Just managed to refresh and even install youtube while my windows pc altstore was off!
> 
> 
> 
> I did somehow had this error: -36607 even with a brand new apple account. Installing the alstore app first on my pc on my i device and then using the wifi refresh from altserver script works!
> 
> 
> 
> It even let's netmuxd run in the background, so it's super user friendly to keep you're apps signed!
> 
> 
> 
> What i did to test this:
> 
> 1. Download the architecture of your choice here: https://github.com/powenn/AltServer-Linux-ShellScript/releases/tag/0.4.0
> 
> 2. unzip it
> 
> 3. Download the right netmuxd here: https://github.com/jkcoxson/netmuxd/releases
> 
> 4. In the run.sh script, i editted the compatibility list to say aarch64 in my case.
> 
> 5. I removed the certificate on my idevice, and first plugged it into my main pc, installed altstore on it.
> 
> 6. I also signed in, refreshed once more with cable
> 
> 7. then refresh but withoud cable (still works)
> 
> 8. refresh again but now i closed altserver on my win (fails, can't find the server)
> 
> 9. back to the linux machine, run the file with: sudo bash run.sh
> 
> 10. on your idevice, refresh and it should work!
> 
> 11. Install cercube with: https://routinehub.co/shortcut/13064/ (yes shameless self-advert)
> 
> 12. Enjoy!
> 
> 
> 
> Big thanks to everyone again :) i looked out doing this for months! Can't wait for pownn to add the arch's he could also verify that work and be supported officially :D 

Few hours later, I could use pinebook pro and some x86_64 VMs to do the test for WiFi refreshing,if works I will push the new release soon

**Comment by powenn** [comment]
@Macleykun You succeeded with modifying script by yourself ?
I am testing it,but both VM and pinebook pro not working,probably I missed something

**Comment by Macleykun** [comment]
> @Macleykun You succeeded with modifying script by yourself ? I am testing it,but both VM and pinebook pro not working,probably I missed something

yup, for me it worked, i just replaced the x86_64 bit with aarch64 for me.

have ya also did the step jkcoxson suggested?

This step is done after downloading the release from you, and replacing xxx8801E.mobiledevicepairing on /var/lib/lockdown/xxx8801E.plist

believe you only need to do this once :)

**Comment by powenn** [comment]
> > @Macleykun You succeeded with modifying script by yourself ? I am testing it,but both VM and pinebook pro not working,probably I missed something
> 
> 
> 
> yup, for me it worked, i just replaced the x86_64 bit with aarch64 for me.
> 
> 
> 
> have ya also did the step jkcoxson suggested?
> 
> 
> 
> This step is done after downloading the release from you, and replacing xxx8801E.mobiledevicepairing on /var/lib/lockdown/xxx8801E.plist
> 
> 
> 
> believe you only need to do this once :)

It's already been the right file format

**Comment by powenn** [comment]
And on x86_64 arch,it displays failed to create heartbeat

**Comment by powenn** [comment]
But it's weird,it shouldn't happen, I am just doing what you did,it should work fine

**Comment by powenn** [comment]
Need testers for WiFi refresh 

https://github.com/powenn/AltServer-Linux-ShellScript/releases/tag/0.4.1

**Comment by Macleykun** [comment]
> Need testers for WiFi refresh
> 
> https://github.com/powenn/AltServer-Linux-ShellScript/releases/tag/0.4.1

just tested this, works out of the box with wifi refresh!
(i'm a bit hesitant to switch to usb tethered mode as i have altstore working with youtube).

**Comment by Macleykun** [comment]
Hey @powenn have you been able to look into this?
