### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by Macleykun** [powenn/AltServer-Linux-ShellScript#46]
Heya, jkcoxson got the wifi refresh working (we didn't get error's etc)

But, when i tried to install altstore i got this error?

![image](https://user-images.githubusercontent.com/26381427/197252329-29e4b179-e7c7-498f-85e4-a13990bef46c.png)

What i'm doing wrong?

**Comment by Deathproof76** [comment]
same problem here

**Comment by Macleykun** [comment]
thanks!
Sadly now i'm stuck on error -36607, but i've heard that will go away from itself (apple server sided)?

**Comment by powenn** [comment]
> thanks!
> Sadly now i'm stuck on error -36607, but i've heard that will go away from itself (apple server sided)?

Yes , just wait few hours or few days

**Comment by Macleykun** [comment]
Somehow i had this also with a brand new apple account.
I installed with the normal methode on windows, but then using wifi refresh with AltServer-linux-ShellScript!

**Comment by Macleykun** [comment]
Heya, the problem was the anisette!
Had to setup this on a different host with x86_64: https://github.com/NyaMisty/AltServer-Linux/releases/tag/v0.0.5#:~:text=Run%20AltServer%2DLinux-,Custom%20Anisette%20Server,-Many%20user%20have

1. Pull and run [alt_anisette_server](https://hub.docker.com/r/nyamisty/alt_anisette_server) according to README.
2. Run export ALTSERVER_ANISETTE_SERVER="http://192.168.1.2:6969" before AltServer-Linux each time (replace the 192.168.1.2 to your server IP)
3. Run AltServer-Linux

**Comment by powenn** [comment]
Hi @Macleykun 

I have rewrite https://github.com/powenn/AltServer-Linux-PyScript
Now it's support WiFI Installation and add anisette server fix
But one last problem left is WiFI refreshing not working
So I want to ask you for helping testing

And how did you get WiFi refreshing before ?
