### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by qwertykey2468** [powenn/AltServer-Linux-ShellScript#5]
When running in Android Termux default environment, the same error occurs as the questioner below. > " Exec format error "

When running in an environment where Ubuntu was installed in Termux, a " Segmentation fault error " occurred with random numbers.

Does it not support the ARM environment at all? But to say that, it worked well in the ish shell (ios environment), I don't know if it's working because there's no USB cable to connect between iPhone and iPhone.

(The translation may be weird using a translator)

**Comment by powenn** [comment]
> When running in Android Termux default environment, the same error occurs as the questioner below. > " Exec format error "
> 
> 
> 
> When running in an environment where Ubuntu was installed in Termux, a " Segmentation fault error " occurred with random numbers.
> 
> 
> 
> Does it not support the ARM environment at all? But to say that, it worked well in the ish shell (ios environment), I don't know if it's working because there's no USB cable to connect between iPhone and iPhone.
> 
> 
> 
> (The translation may be weird using a translator)

I know,ish can exec but termux can't,that's weird,seems not support arm at all.

**Comment by qwertykey2468** [comment]
> > Android Termux 기본 환경에서 실행할 때 아래 질문자와 동일한 오류가 발생합니다. > " Exec 형식 오류 "
> > 우분투가 Termux에 설치된 환경에서 실행할 때 " 세분화 오류 오류"가 난수로 발생했습니다.
> > ARM 환경을 전혀 지원하지 않습니까? 하지만 그 말을, 그것은 ish shell에서 잘 작동 (ios 환경), 아이폰과 아이폰 사이 연결 하는 USB 케이블 이 없기 때문에 작동 하는 경우 나도 몰라.
> > (번역을 사용하여 번역이 이상할 수 있음)
> 
> 나는 알고,ish 는 임원 수 있지만 termux 수 없습니다,그건 이상한,전혀 팔을 지원하지 않는 것 같다.

Is there a way to do it without cable?  I just did it on Linux Mint and it's working well.. Is the Segmentation fault error occurring in the Termux + Ubuntu environment also related to Arm architecture issues?

> > When running in Android Termux default environment, the same error occurs as the questioner below. > " Exec format error "
> > When running in an environment where Ubuntu was installed in Termux, a " Segmentation fault error " occurred with random numbers.
> > Does it not support the ARM environment at all? But to say that, it worked well in the ish shell (ios environment), I don't know if it's working because there's no USB cable to connect between iPhone and iPhone.
> > (The translation may be weird using a translator)
> 
> I know,ish can exec but termux can't,that's weird,seems not support arm at all.

Is there a way to do it without cable?  I just did it on Linux Mint and it's working well.. Is the Segmentation fault error occurring in the Termux + Ubuntu environment also related to Arm architecture issues?

**Comment by powenn** [comment]
> > I know,ish can exec but termux can't,that's weird,seems not support arm at all.
> 
> 
> 
> Is there a way to do it without cable?  I just did it on Linux Mint (x64) and it's working well.. Is the Segmentation fault error occurring in the Termux + Ubuntu environment also related to Arm architecture issues?

I am not really sure about it, I will do some test
