### ISSUE TITLE
Failed to create heartbeat client for udid ........  UnknownError

### ISSUE THREAD

**Issue by viernae** [powenn/AltServer-Linux-ShellScript#51]
I am running armbian on rpi 4. The tethered mode works fine but when I try to use wifi Daemode mode I get this error

` [2023-01-26T19:47:03Z ERROR netmuxd::heartbeat] Failed to create heartbeat client for udid e7041f2d2b3a832d433b733c280d99d09f337f26: UnknownError`

I tried first using tethered mode and pairing it and switching to wifi mode and I still get the error. I tried multiple things, but it still does not work. Now I am thinking that it may just not run on armbian. If so, will you ever make it run on ambian?

**Comment by powenn** [comment]
switch to tethered mode and replug device then pair it should solve it ,and seems wifi mode for arm still having issues

**Comment by viernae** [comment]
yea thanks its not giving me that error but when i try to refresh/sideload any ipa it just says "Could not find AltServer"

**Comment by viernae** [comment]
i tried playing with it for example like refreshing on tethered mode and midway switching it to wireless and it seems that netmuxd is either not working or altstore is not woking

**Comment by powenn** [comment]
All required dependencies installed ?

**Comment by powenn** [comment]
Also there is no WiFi installation support,only refresh support but seems having issues on arm

**Comment by viernae** [comment]
> All required dependencies installed ?

I believe so. is it possible its a problem with armbian ?

**Comment by viernae** [comment]
i got it fixed.

**Comment by AlyafeiAli** [comment]
> i got it fixed.

How? I'm facing the same issue.
