### ISSUE TITLE
Help me using altserver in termux (android)

### ISSUE THREAD

**Issue by DermonPelado** [powenn/AltServer-Linux-ShellScript#52]
Hi, I installed debian in termux, I’m new in this so sorry if I don’t understand

first I installed this:
sudo apt-get install usbmuxd libimobiledevice6 libimobiledevice-utils

sudo apt-get install wget curl libavahi-compat-libdnssd-dev

and then cloned the repository and executed the shell script
But when I select the option w, termux show this:
Starting netmuxd
Starting mDNS discovery for _apple-mobdev2._tcp.local with mdns
Listening on /var/run/usbmuxd

And then nothing more happens, idk why. I only want to refresh apps with wifi, I have the app installed in my iPhone, please help, what I have to do? Thanks!

**Comment by powenn** [comment]
you should get it from release rather than clone from repo

**Comment by DermonPelado** [comment]
From release was the same problem

**Comment by powenn** [comment]
No, get from release is for make sure you can update it easily, since you run the script ,it already start the wife daemon and able to refresh signed apps

**Comment by DermonPelado** [comment]
Ok but how can I refresh apps without connecting with cable my iPhone in my android? I have already installed AltStore in my iPhone from windows

**Comment by DermonPelado** [comment]
Like, what is the wifi daemon waiting?

**Comment by powenn** [comment]
I didn't test with android phones, so try with press refresh button in AltStore on your iOS device

**Comment by DermonPelado** [comment]
But what I have to do after I ran the shellscript and the WiFi daemon is starting? Like the next step

**Comment by powenn** [comment]
there is no next step

**Comment by DermonPelado** [comment]
Refreshing an app in iOS is the way to proof it’s working after that?
