### ISSUE TITLE
Unknown: Refer back to AltScript

### ISSUE THREAD

**Issue by TNTReeOnLinux** [powenn/AltServer-Linux-ShellScript#53]
Right so basically, I was following a tutorial and I followed everything correctly and yet I kept getting the error Unknown Refer back to AltScript, Option:, I've tried updating my OS but, it was completely up to date, and then I tried deleting the AltServer linux files, reinstalling them through the github page, and yet the same thing happened Unknown Refer Back To AltScript

**Comment by leeporcodi** [comment]
same problem

**Comment by powenn** [comment]
You sure about that you are talking about this project?

**Comment by Cosmonear** [comment]
Yes, I have the same problem.
Here are the print : 

```
OPTIONS

  1, --Install AltStore
    Install AltStore to your device
  2, --Install ipa files
    Install ipa files to your device
  b, --Back
    Back to previous script
Enter OPTION to continue
1
Please provide your AppleID
xxx@gmail.com
Please provide the password of AppleID
xxxxx
Unknown options: xxx@gmail.com ./AltStore.ipa 
Do you want to save this Account ? [y/n]
y
saved
<<  Back to AltServer script  >>
Enter OPTION to continue
```

**Comment by powenn** [comment]
You have to switch to tether mode for installation with -t option , there is no support for wifi installation

**Comment by Cosmonear** [comment]
Is it not in USB mode by default ? I tried tethered too, but it's not working. When i use -p it says "No device found.".
But with lsusb I have this : Bus 001 Device 003: ID 05ac:12a8 Apple, Inc. iPhone 5/5C/5S/6/SE
So I d'ont understand why it is not working.

**Comment by powenn** [comment]
Switch to tether mode,plug in device then pair
