### ISSUE TITLE
./AltServer: line 1: Not: command not found

### ISSUE THREAD

**Issue by LLuanZZ** [powenn/AltServer-Linux-ShellScript#56]
When I'm going to install AltServer, even typing the Apple ID and the right password, it gives this error: 

`. /AltServer: line 1: Not: command not found`

**Comment by powenn** [comment]
You might run the script in the wrong dir

**Comment by LLuanZZ** [comment]
> Você pode executar o script no diretório errado

E qual seria o certo?

**Comment by LLuanZZ** [comment]
> You might run the script in the wrong dir

What would be the right directory?

**Comment by powenn** [comment]
The dir contains AltServer binary

**Comment by powenn** [comment]
https://github.com/powenn/AltServer-Linux-ShellScript/issues/53

**Comment by LLuanZZ** [comment]
i686

**Comment by powenn** [comment]
https://github.com/NyaMisty/AltServer-Linux/releases

**Comment by powenn** [comment]
There is no i686 release 
Probably i586 one works , just try some of them
Download and rename to AltServer then place it inside the dir

**Comment by LLuanZZ** [comment]
A file with that name already exists, should I replace it?

**Comment by powenn** [comment]
Replace it

**Comment by LLuanZZ** [comment]
Now just run the script?

**Comment by LLuanZZ** [comment]
now this is showing:

`Press any key to continue...`

**Comment by LLuanZZ** [comment]
![Captura de tela_2023-04-10_21-06-55](https://user-images.githubusercontent.com/108953018/231022524-5f01a544-d790-436a-b402-a01db1121a72.png)

**Comment by powenn** [comment]
Then there is nothing I can help,there's no script issue,the worst solution is compile AltServer manually for your machine architecture
