### ISSUE TITLE
Altstore crash on launch. removing app prevents reinstall

### ISSUE THREAD

**Issue by Altirix** [powenn/AltServer-Linux-ShellScript#6]
Iphone 13 ios 15.2 Altstore crashes on start up. even with new apple id

Removing the app and attempting to install with the same apple id you get stuck at `A device with number 'Device ID' already exists on this team. (35)` cant seem to find any info on how you fix this except making a brand new apple id

daemon.sh gets stuck at `Starting notification connection to device:` when attempting to open altstore

**Comment by powenn** [comment]
> Iphone 13 ios 15.2 Altstore crashes on start up. even with new apple id
> 
> 
> 
> Removing the app and attempting to install with the same apple id you get stuck at `A device with number 'Device ID' already exists on this team. (35)` cant seem to find any info on how you fix this except making a brand new apple id
> 
> 
> 
> daemon.sh gets stuck at `Starting notification connection to device:` when attempting to open altstore

I think iOS 15 not support

**Comment by powenn** [comment]
Please try the latest release, this issue should be solved

**Comment by powenn** [comment]
Device id error,was cause by UDID ,solved
