### ISSUE TITLE
Could not install Altstore.ipa to unknow  - python script

### ISSUE THREAD

**Issue by BleakFox** [powenn/AltServer-Linux-ShellScript#62]
after that comment, i re tried it, and i discovered tht the error was beacouse I ned to write the email of my apple id with the correct capital letters. Today I tried to install spotify with altstore, but when i did the same things, this error appeared:

```
Could not install AltStore.ipa to unknown.
    Incorrect Content-Type: must be textual to extract_string, JSON to extract_json.
Press any key to continue.
```

This after I did the update of the script (the python script that u told me to use)
Do u know how to fix it?

**Comment by powenn** [comment]
This is shell scipt edition , wrong place to open issue
