### ISSUE TITLE
Need someone help to test on rooted android

### ISSUE THREAD

**Issue by powenn** [powenn/AltServer-Linux-ShellScript#7]
Who have rooted android phones,I think AltServer-armv7 is possible to run on it,I have only tested that is executable on normal android phones,I can't mount iPhone,seems only rooted android phones can,not sure so much, I need someone help to test

**Comment by qwertykey2468** [comment]
Oh, that's good, it works well.

But In a termux environment, how do I connect between ios android? Both OTG and C to 8pin cables are not recognized.

**Comment by qwertykey2468** [comment]
> Who have rooted android phones,I think AltServer-armv7 is possible to run on it,I have only tested that is executable on normal android phones,I can't mount iPhone,seems only rooted android phones can,not sure so much, I need someone help to test

Oh, that's good, it works well.

But In a termux environment, how do I connect between ios android? Both OTG and C to 8pin cables are not recognized.

**Comment by powenn** [comment]
> > Who have rooted android phones,I think AltServer-armv7 is possible to run on it,I have only tested that is executable on normal android phones,I can't mount iPhone,seems only rooted android phones can,not sure so much, I need someone help to test
> 
> 
> 
> Oh, that's good, it works well.
> 
> 
> 
> But In a termux environment, how do I connect between ios android? Both OTG and C to 8pin cables are not recognized.

Like people used to jailbreak with Checkra1n?
I notice that if u go to file app on android , iPhone will display that to trust this computer

**Comment by qwertykey2468** [comment]
> > > Who have rooted android phones,I think AltServer-armv7 is possible to run on it,I have only tested that is executable on normal android phones,I can't mount iPhone,seems only rooted android phones can,not sure so much, I need someone help to test
> > 
> > 
> > Oh, that's good, it works well.
> > But In a termux environment, how do I connect between ios android? Both OTG and C to 8pin cables are not recognized.
> 
> Like people used to jailbreak with Checkra1n? I notice that if u go to file app on android , iPhone will display that to trust this computer

Oh, it's coming up, but "Allowed" is coming up. There's nothing I can do but search for pictures in this state.

**Comment by powenn** [comment]
> 
> 
> 
> 
> > > > Who have rooted android phones,I think AltServer-armv7 is possible to run on it,I have only tested that is executable on normal android phones,I can't mount iPhone,seems only rooted android phones can,not sure so much, I need someone help to test
> 
> > > 
> 
> > > 
> 
> > > Oh, that's good, it works well.
> 
> > > But In a termux environment, how do I connect between ios android? Both OTG and C to 8pin cables are not recognized.
> 
> > 
> 
> > Like people used to jailbreak with Checkra1n? I notice that if u go to file app on android , iPhone will display that to trust this computer
> 
> 
> 
> Oh, it's coming up, but "Allowed" (no trust) is coming up. There's nothing I can do but search for pictures in this state.

Is idevicepair pair work?
Have u run termux-setup-storage before,I really don't know how Checkra1n did it

**Comment by qwertykey2468** [comment]
> Is idevicepair pair work? Have u run termux-setup-storage before,I really don't know how Checkra1n did it

If use the 'idevicepair pair' command, it says 'the device cannot be found'.
The condition is the same even with termux-setup-storage.

**Comment by powenn** [comment]
> > Is idevicepair pair work? Have u run termux-setup-storage before,I really don't know how Checkra1n did it
> 
> 
> 
> If use the 'idevicepair pair' command, it says 'the device cannot be found'.
> 
> The condition is the same even with termux-setup-storage. 

how about su and then lsusb

**Comment by qwertykey2468** [comment]
> how about su and then lsusb

I think there's a slight error with "su".. 

Is lsusb a command to show us the USB list? When I used it, it showed that the device was not recognized when it was not connected, and that three devices were recognized when it was connected (c to 8pin cable) .

**Comment by powenn** [comment]
> > how about su and then lsusb
> 
> 
> 
> I think there's a slight error with "su".. 
> 
> 
> 
> Is lsusb a command to show us the USB list? When I used it, it showed that the device was not recognized when it was not connected, and that three devices were recognized when it was connected (c to 8pin cable) .

Yes,lsusb is the command to do that

**Comment by powenn** [comment]
> > how about su and then lsusb
> 
> 
> 
> I think there's a slight error with "su".. 
> 
> 
> 
> Is lsusb a command to show us the USB list? When I used it, it showed that the device was not recognized when it was not connected, and that three devices were recognized when it was connected (c to 8pin cable) .

How about using usb c to lightning

**Comment by qwertykey2468** [comment]
> How about using usb c to lightning

If you plug the devices into each other with a c to lighting cable, lsusb recognizes it..

"idevicepair" is not recognizing it because there's no window asking for trust.. I have to look at the window asking for trust, but I don't know what else to do.

**Comment by qwertykey2468** [comment]
> How about using usb c to lightning

Oh, awesome,,,, I tested it on Ubuntu Touch, but it didn't work at first, but when I used the usbmuxd-f-v command, the pairing worked well.

I think Android will be able to connect if it uses that command. I'll test it out.

**Comment by powenn** [comment]
> > How about using usb c to lightning
> 
> 
> 
> Oh, awesome,,,, I tested it on Ubuntu Touch, but it didn't work at first, but when I used the usbmuxd-f-v command, the pairing worked well.
> 
> 
> 
> I think Android will be able to connect if it uses that command. I'll test it out.
> 
> 

And then please tell me your test result

**Comment by qwertykey2468** [comment]
experimented in many different environments on Android termux.

The termux basic environment, termux+ubuntu environment, and termux+debian environment all seem to have USB-related errors. Usbmxud doesn't recognize it as a whole,,, I should use Ubuntu Touch again.

**Comment by powenn** [comment]
> > And then please tell me your test result
> 
> 
> 
> experimented in many different environments on Android termux.
> 
> 
> 
> The termux basic environment, termux+ubuntu environment, and termux+debian environment all seem to have USB-related errors. Usbmxud doesn't recognize it as a whole,,, I should use Ubuntu Touch again.

At least Linux phone works well,we have great AltServer portable solution,could you help me to test the pre release ?
And tell me did it become more convenient, I added several features like save account,use saved account,select ipa by enter number,and it only needs one command ./run.sh

**Comment by qwertykey2468** [comment]
> At least Linux phone works well,we have great AltServer portable solution,could you help me to test the pre-release ? And tell me did it become more convenient, I added several features like save account,use saved account,select ipa by enter number,and it only needs one command ./run.sh

Oh, okay. I'll test it right away.

**Comment by qwertykey2468** [comment]
> At least Linux phone works well,we have great AltServer portable solution,could you help me to test the pre-release ? And tell me did it become more convenient, I added several features like save account,use saved account,select ipa by enter number,and it only needs one command ./run.sh

The daemon mode works well, so I think all functions will work normally.

**Comment by powenn** [comment]
> > At least Linux phone works well,we have great AltServer portable solution,could you help me to test the pre-release ? And tell me did it become more convenient, I added several features like save account,use saved account,select ipa by enter number,and it only needs one command ./run.sh
> 
> 
> 
> The daemon mode works well, so I think all functions will work normally.
> 
> 

Okay, thanks for the test, I have simplified the script few moments ago,now being easier to read and understand

**Comment by powenn** [comment]
New release !!

features added:

account saving
enter number to select and use saved account
enter number to select ipa
only need one command to use the script ./run.sh
Daemon mode will start automatically after device connected and press Enter
